esphome:
  name: laserfanlightcontroller
  friendly_name: LaserFanLightController

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xkskBSD9CWd9+5YAnDXGJa1soc2YNE/t7TMmcdEriIY="

ota:
  password: "92755ee233b3ed7d2fe716ac064114c7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Laserfanlightcontroller"
    password: "Y9EKY6GcTeZ3"

captive_portal:
  
switch:
   - platform: gpio
     pin: D1
     id: LaserAbsaugung
     name: "Laser Absaugung"
     inverted: False

# Example configuration entry
sensor:
  - platform: adc
    pin: A0
    name: "LaserAbsaugungSpannung"
    update_interval: 1s
    on_value_range:
      - above: 0.11
        then:
          - switch.turn_on: LaserAbsaugung
      - below: 0.1
        then:
          - switch.turn_off: LaserAbsaugung