esphome:
  name: "laserpowercontroller"
  friendly_name: LaserPowerController

esp32:
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Le+Tz+D7sUiYWD+joEGq2K3lRCWWmQjAJ9JQAY0GIA4="

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "LaserPowerController"
    password: "ymo4qKbSlU0g"

captive_portal:
    
switch:
   - platform: gpio
     pin: GPIO2
     id: LaserPowerControllerLED
     name: "Laser Power Controller LED"
     inverted: True
