esphome:
  name: marble-machine
  friendly_name: Marble Machine

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rzQR/rvoz5d2lRi6kFoiWcEzXIxnYQmP2Sf8vY5H6F0="

ota:
  - platform: esphome
    password: "e784516737ac597ce8707bd1df1149c0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Marble-Machine Fallback Hotspot"
    password: "09rTcGyWaJBl"

captive_portal:

stepper:
  - platform: uln2003
    id: my_stepper
    pin_a: D1
    pin_b: D2
    pin_c: D5
    pin_d: D6
    max_speed: 500 steps/s
    sleep_when_done: true
    step_mode: FULL_STEP

# Switch to control the motor
switch:
  - platform: template
    name: "Motor Switch"
    id: motor_switch
    optimistic: true
  - platform: gpio
    pin: D4
    name: "LED"
    id: led_switch
    inverted: true
    restore_mode: ALWAYS_OFF

# Slider to control the speed
number:
  - platform: template
    name: "Motor Speed"
    id: motor_speed
    min_value: 10
    max_value: 500
    initial_value: 500
    step: 10
    unit_of_measurement: "steps/s"
    optimistic: True
    set_action:
      - stepper.set_speed:
          id: my_stepper
          speed: !lambda 'return x;'
      - logger.log:
          level: DEBUG
          format: "Motor Speed: %f"
          args: [ 'id(motor_speed).state' ]

  - platform: template
    name: "Stepper Control"
    min_value: -1000
    max_value: 1000
    initial_value: 0
    step: 10
    set_action:
      - stepper.set_target:
          id: my_stepper
          target: !lambda 'return x;'

  - platform: template
    name: "Step Count"
    id: step_count
    min_value: 50
    max_value: 1000
    initial_value: 300
    step: 50
    unit_of_measurement: "steps"
    optimistic: True

# Sensor to show current steps
sensor:
  - platform: template
    name: "Current Steps"
    id: current_steps
    unit_of_measurement: "steps"
    lambda: |-
      return id(my_stepper).current_position;

interval:
  - id: motor_interval
    interval: 5s
    then:
      if:
        condition:
          switch.is_on: motor_switch
        then:
          - stepper.set_speed:
              id: my_stepper
              speed: !lambda 'return id(motor_speed).state;'
          - stepper.set_target:
              id: my_stepper
              target: !lambda 'return id(my_stepper).current_position - id(step_count).state;'
          - sensor.template.publish:
              id: current_steps
              state: !lambda 'return id(my_stepper).current_position;'