api:
  encryption:
    key: "gFbP//jNKmM/dJOIf01jrac4GrxIHdJZGz39XrjiaQ8="
substitutions:

###### CHANGE ME START ######

  device_name: "nspanelworkshop" 
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  nextion_update_url: "http://192.168.178.150/nspanel_eu.tft" # URL to local tft File on SYNOLOGY NAS
#  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/raw/main/nspanel_eu.tft" # URL to Github

##### CHANGE ME END #####



##### DO NOT CHANGE ANYTHING! #####

packages:
  ##### download esphome code from Github
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: beta
    files: [nspanel_esphome.yaml]
    refresh: 300s

##### DO NOT CHANGE ANYTHING! #####
